"""adds healer model relationship with crystal

Revision ID: 348b43e1ec03
Revises: 713ac4aa1fc9
Create Date: 2023-05-09 10:20:06.593798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348b43e1ec03'
down_revision = '713ac4aa1fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crystal', sa.Column('healer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crystal', 'healer', ['healer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crystal', type_='foreignkey')
    op.drop_column('crystal', 'healer_id')
    # ### end Alembic commands ###
