"""adds healer model

Revision ID: 713ac4aa1fc9
Revises: ad07bdd5c63c
Create Date: 2023-05-09 10:00:57.615668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713ac4aa1fc9'
down_revision = 'ad07bdd5c63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('healer')
    # ### end Alembic commands ###
